### ISSUE TITLE
New License?

### ISSUE THREAD

**Issue by ChelonianEgghead** [ChelonianEggheadProductions/GrowMaster#1]
As always, I have acted without thinking twice.  :(  When I chose the GNU GPL v3 as the license for this project, I did so simply because it seemed to be the most common. I have read some of it, but I never got around to finishing it, so I have only just learned about the sections concerning DRM, and the requirment that if any code licensed under the GPL is re-used in another program, that entire program must be licensed under the GPL as well. Now, I'm no lawyer, and I have trouble understanding most of this legal jargon, (in fact, I have no idea what the part about DRM even means!) but I'm starting to wonder if this is the right free software license for my project. The good news is that all I've got right now is a "Hello, World!" file, so there can't possibly be any derivative works as of July 2016, but I want the authors of derivative works to be able to choose their own license once the program is finished. Any suggestions?

**Comment by Dumbbird1** [comment]
Nobody cares...........

**Comment by Randomcrap** [comment]
OMG DUMBBIRD I AM ONE OF YOU FANS FROM YOUTUBE LOL THATS SO FUNNY XD
Its to bad your comment got deleted :(

**Comment by Dumbbird1** [comment]
I hope you have learned your lesson.

(You really should close this issue.)

**Comment by ChelonianEgghead** [comment]
Never mind, I do want the clauses concerning DRM. I guess it's not too much of a problem that derivative works have to use this license, so I guess I'll stick with it.
